version: '3'
services:
  article-insight-ai:
    container_name: article-insight-ai
    image: article-insight-ai:latest
    ports:
      - "32910:8080"
    volumes:
      - ./config:/config
      - ./templates:/templates
      - ./static:/static
    labels:
      keep: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - docker-app-network

networks:
  docker-app-network:
    external: true